export const STATUSES = {
  BREAK: 'BREAK',
  FOCUS: 'FOCUS',
  STOPPED: 'STOPPED'
}


export const NOTIFICATION_STATUS = {
  DENIED: 'DENIED',
  DISABLED: 'DISABLED',
  ENABLED: 'ENABLED',
  UNCONFIRMED: 'UNCONFIRMED'
}
